-- Catch-up consolidada: login, usuários admin, leilões, views e RLS.
-- Idempotente — pode rodar mesmo se parte das migrations antigas nunca foi aplicada.
-- Complementa 20260704180000 / 20260704190000 / 20260704200000 (já rodadas).
--
-- Cobre o que o app VistoriaPro precisa para:
--   • Login (public.usuarios + coluna ativo)
--   • Gerir usuários (SELECT / INSERT / UPDATE)
--   • Gerir leilões (SELECT / INSERT / UPDATE / DELETE)
--   • Listar vistorias por leilão (view vistorias_com_leilao)
--   • Realtime em leiloes + vistorias
--
-- NÃO recria dados nem apaga vistorias/leilões existentes.

-- =============================================================================
-- 1) Função updated_at (compartilhada por leiloes e vistorias)
-- =============================================================================
CREATE OR REPLACE FUNCTION public.set_updated_at()
RETURNS TRIGGER
LANGUAGE plpgsql
AS $$
BEGIN
  NEW.updated_at = now();
  RETURN NEW;
END;
$$;

-- =============================================================================
-- 2) public.leiloes — CRUD na tela /leiloes + Home + sync
-- =============================================================================
CREATE TABLE IF NOT EXISTS public.leiloes (
  id          bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  nome        text NOT NULL,
  created_at  timestamptz NOT NULL DEFAULT now(),
  updated_at  timestamptz NOT NULL DEFAULT now(),
  created_by  text
);

ALTER TABLE public.leiloes
  ADD COLUMN IF NOT EXISTS created_at timestamptz DEFAULT now(),
  ADD COLUMN IF NOT EXISTS updated_at timestamptz DEFAULT now(),
  ADD COLUMN IF NOT EXISTS created_by text;

UPDATE public.leiloes
SET updated_at = COALESCE(created_at, now())
WHERE updated_at IS NULL;

UPDATE public.leiloes
SET created_at = COALESCE(created_at, now())
WHERE created_at IS NULL;

ALTER TABLE public.leiloes
  ALTER COLUMN created_at SET DEFAULT now(),
  ALTER COLUMN updated_at SET DEFAULT now();

DO $$
BEGIN
  IF EXISTS (
    SELECT 1 FROM information_schema.columns
    WHERE table_schema = 'public' AND table_name = 'leiloes'
      AND column_name = 'updated_at' AND is_nullable = 'YES'
  ) THEN
    ALTER TABLE public.leiloes ALTER COLUMN updated_at SET NOT NULL;
  END IF;
  IF EXISTS (
    SELECT 1 FROM information_schema.columns
    WHERE table_schema = 'public' AND table_name = 'leiloes'
      AND column_name = 'created_at' AND is_nullable = 'YES'
  ) THEN
    ALTER TABLE public.leiloes ALTER COLUMN created_at SET NOT NULL;
  END IF;
EXCEPTION
  WHEN others THEN NULL;
END $$;

DROP TRIGGER IF EXISTS set_leiloes_updated_at ON public.leiloes;
CREATE TRIGGER set_leiloes_updated_at
  BEFORE UPDATE ON public.leiloes
  FOR EACH ROW
  EXECUTE FUNCTION public.set_updated_at();

CREATE INDEX IF NOT EXISTS idx_leiloes_nome ON public.leiloes (nome);

-- =============================================================================
-- 3) public.usuarios — login + tela /usuarios
-- =============================================================================
CREATE TABLE IF NOT EXISTS public.usuarios (
  id         uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  nome       text NOT NULL,
  senha      text NOT NULL,
  role       text NOT NULL CHECK (role IN ('vistoriador', 'admin')),
  created_at timestamptz NOT NULL DEFAULT now(),
  ativo      boolean NOT NULL DEFAULT true
);

ALTER TABLE public.usuarios
  ADD COLUMN IF NOT EXISTS created_at timestamptz DEFAULT now(),
  ADD COLUMN IF NOT EXISTS ativo boolean NOT NULL DEFAULT true;

UPDATE public.usuarios SET ativo = true WHERE ativo IS NULL;

CREATE UNIQUE INDEX IF NOT EXISTS usuarios_nome_unique
  ON public.usuarios (nome);

COMMENT ON TABLE public.usuarios IS
  'Login VistoriaPro: nome + senha (PIN 4 dígitos). role: vistoriador|admin. ativo=false bloqueia login.';
COMMENT ON COLUMN public.usuarios.ativo IS
  'false = usuário desativado; não aparece no login e não autentica.';

-- =============================================================================
-- 4) public.vistorias — colunas usadas pelo app (se faltarem)
-- =============================================================================
ALTER TABLE public.vistorias
  ADD COLUMN IF NOT EXISTS external_id text,
  ADD COLUMN IF NOT EXISTS created_by text,
  ADD COLUMN IF NOT EXISTS updated_at timestamptz DEFAULT now(),
  ADD COLUMN IF NOT EXISTS url_foto text,
  ADD COLUMN IF NOT EXISTS baixado_pc boolean DEFAULT false;

CREATE UNIQUE INDEX IF NOT EXISTS vistorias_external_id_unique
  ON public.vistorias (external_id)
  WHERE external_id IS NOT NULL;

-- =============================================================================
-- 5) public.vistorias_leiloes — vínculo N:1 (se ainda não existir)
-- =============================================================================
CREATE TABLE IF NOT EXISTS public.vistorias_leiloes (
  id          bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  vistoria_id uuid NOT NULL REFERENCES public.vistorias (id) ON DELETE CASCADE,
  leilao_id   bigint NOT NULL REFERENCES public.leiloes (id) ON DELETE CASCADE
);

CREATE UNIQUE INDEX IF NOT EXISTS vistorias_leiloes_vistoria_leilao_unique
  ON public.vistorias_leiloes (vistoria_id, leilao_id);

CREATE INDEX IF NOT EXISTS idx_vistorias_leiloes_leilao_id
  ON public.vistorias_leiloes (leilao_id);

-- =============================================================================
-- 6) Views usadas pelo app (pull histórico, duplicidade, app consumidor)
--     DROP antes de CREATE: CREATE OR REPLACE não pode remover colunas da view.
-- =============================================================================
DROP VIEW IF EXISTS public.vistorias_fotos_com_leilao CASCADE;
DROP VIEW IF EXISTS public.vistorias_com_leilao CASCADE;

CREATE VIEW public.vistorias_com_leilao AS
SELECT
  v.*,
  vl.leilao_id,
  vl.leilao_id AS leilao
FROM public.vistorias v
INNER JOIN public.vistorias_leiloes vl ON vl.vistoria_id = v.id;

DO $$
BEGIN
  IF EXISTS (
    SELECT 1 FROM information_schema.tables
    WHERE table_schema = 'public' AND table_name = 'vistorias_fotos'
  ) THEN
    EXECUTE 'DROP VIEW IF EXISTS public.vistorias_fotos_com_leilao CASCADE';
    EXECUTE $v$
      CREATE VIEW public.vistorias_fotos_com_leilao AS
      SELECT
        vf.id,
        vf.vistoria_id,
        vf.tipo,
        vf.ordem,
        vf.storage_path,
        vf.arquivo_original,
        vf.mime_type,
        vf.tamanho,
        vf.uploaded_at,
        vf.sha256,
        vf.created_at,
        v.placa,
        v.num_vistoria,
        v.external_id AS vistoria_external_id,
        vl.leilao_id
      FROM public.vistorias_fotos vf
      JOIN public.vistorias v ON v.id = vf.vistoria_id
      JOIN public.vistorias_leiloes vl ON vl.vistoria_id = v.id
    $v$;
  END IF;
END $$;

GRANT SELECT ON public.vistorias_com_leilao TO anon, authenticated;

DO $$
BEGIN
  IF EXISTS (
    SELECT 1 FROM information_schema.views
    WHERE table_schema = 'public' AND table_name = 'vistorias_fotos_com_leilao'
  ) THEN
    GRANT SELECT ON public.vistorias_fotos_com_leilao TO anon, authenticated;
  END IF;
END $$;

-- =============================================================================
-- 7) Realtime (idempotente — ignora se já estiver na publication)
-- =============================================================================
DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_publication_tables
    WHERE pubname = 'supabase_realtime'
      AND schemaname = 'public'
      AND tablename = 'leiloes'
  ) THEN
    ALTER PUBLICATION supabase_realtime ADD TABLE public.leiloes;
  END IF;

  IF NOT EXISTS (
    SELECT 1 FROM pg_publication_tables
    WHERE pubname = 'supabase_realtime'
      AND schemaname = 'public'
      AND tablename = 'vistorias'
  ) THEN
    ALTER PUBLICATION supabase_realtime ADD TABLE public.vistorias;
  END IF;
EXCEPTION
  WHEN undefined_table THEN
    RAISE NOTICE 'Publication supabase_realtime não encontrada — habilite Realtime no Dashboard.';
END $$;

-- =============================================================================
-- 8) RLS — leiloes (gerir leilões + Home lista leilões)
-- =============================================================================
ALTER TABLE public.leiloes ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS leiloes_select ON public.leiloes;
DROP POLICY IF EXISTS leiloes_insert ON public.leiloes;
DROP POLICY IF EXISTS leiloes_update ON public.leiloes;
DROP POLICY IF EXISTS leiloes_delete ON public.leiloes;

CREATE POLICY leiloes_select ON public.leiloes
  FOR SELECT TO anon, authenticated USING (true);

CREATE POLICY leiloes_insert ON public.leiloes
  FOR INSERT TO anon, authenticated WITH CHECK (true);

CREATE POLICY leiloes_update ON public.leiloes
  FOR UPDATE TO anon, authenticated USING (true) WITH CHECK (true);

CREATE POLICY leiloes_delete ON public.leiloes
  FOR DELETE TO anon, authenticated USING (true);

-- =============================================================================
-- 9) RLS — usuarios (login + gerir usuários)
-- =============================================================================
ALTER TABLE public.usuarios ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS usuarios_select ON public.usuarios;
DROP POLICY IF EXISTS usuarios_insert ON public.usuarios;
DROP POLICY IF EXISTS usuarios_update ON public.usuarios;
DROP POLICY IF EXISTS usuarios_delete ON public.usuarios;

CREATE POLICY usuarios_select ON public.usuarios
  FOR SELECT TO anon, authenticated USING (true);

CREATE POLICY usuarios_insert ON public.usuarios
  FOR INSERT TO anon, authenticated WITH CHECK (true);

CREATE POLICY usuarios_update ON public.usuarios
  FOR UPDATE TO anon, authenticated USING (true) WITH CHECK (true);

-- Opcional: app não deleta usuários (só desativa). Policy delete liberada para manutenção.
CREATE POLICY usuarios_delete ON public.usuarios
  FOR DELETE TO anon, authenticated USING (true);

-- =============================================================================
-- 10) RLS — vistorias / junction / fotos (reforço se RLS já estiver ativo)
-- =============================================================================
DO $$
BEGIN
  IF EXISTS (SELECT 1 FROM pg_tables WHERE schemaname = 'public' AND tablename = 'vistorias') THEN
    EXECUTE 'ALTER TABLE public.vistorias ENABLE ROW LEVEL SECURITY';
    EXECUTE 'DROP POLICY IF EXISTS vistorias_select ON public.vistorias';
    EXECUTE 'DROP POLICY IF EXISTS vistorias_insert ON public.vistorias';
    EXECUTE 'DROP POLICY IF EXISTS vistorias_update ON public.vistorias';
    EXECUTE 'DROP POLICY IF EXISTS vistorias_delete ON public.vistorias';
    EXECUTE $p$ CREATE POLICY vistorias_select ON public.vistorias FOR SELECT TO anon, authenticated USING (true) $p$;
    EXECUTE $p$ CREATE POLICY vistorias_insert ON public.vistorias FOR INSERT TO anon, authenticated WITH CHECK (true) $p$;
    EXECUTE $p$ CREATE POLICY vistorias_update ON public.vistorias FOR UPDATE TO anon, authenticated USING (true) WITH CHECK (true) $p$;
    EXECUTE $p$ CREATE POLICY vistorias_delete ON public.vistorias FOR DELETE TO anon, authenticated USING (true) $p$;
  END IF;

  IF EXISTS (SELECT 1 FROM pg_tables WHERE schemaname = 'public' AND tablename = 'vistorias_leiloes') THEN
    EXECUTE 'ALTER TABLE public.vistorias_leiloes ENABLE ROW LEVEL SECURITY';
    EXECUTE 'DROP POLICY IF EXISTS vistorias_leiloes_select ON public.vistorias_leiloes';
    EXECUTE 'DROP POLICY IF EXISTS vistorias_leiloes_insert ON public.vistorias_leiloes';
    EXECUTE 'DROP POLICY IF EXISTS vistorias_leiloes_delete ON public.vistorias_leiloes';
    EXECUTE $p$ CREATE POLICY vistorias_leiloes_select ON public.vistorias_leiloes FOR SELECT TO anon, authenticated USING (true) $p$;
    EXECUTE $p$ CREATE POLICY vistorias_leiloes_insert ON public.vistorias_leiloes FOR INSERT TO anon, authenticated WITH CHECK (true) $p$;
    EXECUTE $p$ CREATE POLICY vistorias_leiloes_delete ON public.vistorias_leiloes FOR DELETE TO anon, authenticated USING (true) $p$;
  END IF;

  IF EXISTS (SELECT 1 FROM pg_tables WHERE schemaname = 'public' AND tablename = 'vistorias_fotos') THEN
    EXECUTE 'ALTER TABLE public.vistorias_fotos ENABLE ROW LEVEL SECURITY';
    EXECUTE 'DROP POLICY IF EXISTS vistorias_fotos_select ON public.vistorias_fotos';
    EXECUTE 'DROP POLICY IF EXISTS vistorias_fotos_insert ON public.vistorias_fotos';
    EXECUTE 'DROP POLICY IF EXISTS vistorias_fotos_update ON public.vistorias_fotos';
    EXECUTE 'DROP POLICY IF EXISTS vistorias_fotos_delete ON public.vistorias_fotos';
    EXECUTE $p$ CREATE POLICY vistorias_fotos_select ON public.vistorias_fotos FOR SELECT TO anon, authenticated USING (true) $p$;
    EXECUTE $p$ CREATE POLICY vistorias_fotos_insert ON public.vistorias_fotos FOR INSERT TO anon, authenticated WITH CHECK (true) $p$;
    EXECUTE $p$ CREATE POLICY vistorias_fotos_update ON public.vistorias_fotos FOR UPDATE TO anon, authenticated USING (true) WITH CHECK (true) $p$;
    EXECUTE $p$ CREATE POLICY vistorias_fotos_delete ON public.vistorias_fotos FOR DELETE TO anon, authenticated USING (true) $p$;
  END IF;
END $$;

-- =============================================================================
-- 11) Storage — bucket fotos-vistorias (upload/delete de fotos tipadas)
-- =============================================================================
DROP POLICY IF EXISTS fotos_vistorias_select ON storage.objects;
DROP POLICY IF EXISTS fotos_vistorias_insert ON storage.objects;
DROP POLICY IF EXISTS fotos_vistorias_update ON storage.objects;
DROP POLICY IF EXISTS fotos_vistorias_delete ON storage.objects;

CREATE POLICY fotos_vistorias_select ON storage.objects
  FOR SELECT TO anon, authenticated
  USING (bucket_id = 'fotos-vistorias');

CREATE POLICY fotos_vistorias_insert ON storage.objects
  FOR INSERT TO anon, authenticated
  WITH CHECK (bucket_id = 'fotos-vistorias');

CREATE POLICY fotos_vistorias_update ON storage.objects
  FOR UPDATE TO anon, authenticated
  USING (bucket_id = 'fotos-vistorias')
  WITH CHECK (bucket_id = 'fotos-vistorias');

CREATE POLICY fotos_vistorias_delete ON storage.objects
  FOR DELETE TO anon, authenticated
  USING (bucket_id = 'fotos-vistorias');

-- =============================================================================
-- Diagnóstico pós-migration (rodar manualmente se quiser validar)
-- =============================================================================
-- SELECT tablename FROM pg_publication_tables WHERE pubname = 'supabase_realtime';
-- SELECT relname, relrowsecurity FROM pg_class
--   WHERE relname IN ('leiloes','usuarios','vistorias','vistorias_leiloes','vistorias_fotos');
-- SELECT column_name, data_type FROM information_schema.columns
--   WHERE table_name = 'usuarios' ORDER BY ordinal_position;
-- SELECT count(*) FROM usuarios WHERE ativo = true;
